/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
import{dcLocalStorage as e}from"../../common/local-storage.js";import{STUDY_SPACE_ADD_WEBPAGE_ELIGIBLE_KEY as t}from"../../common/constant.js";import{BROWSER_STUDENT_STATE_KEY as n,STUDY_SPACE_EXPERIENCE_ENABLED_KEY as o,STUDY_SPACE_EXPERIENCE_PREFERENCE_SET_KEY as s,ENGAGEMENT_STATE_TAG_FIELD as r}from"./constants.js";import{isStudySpaceExperienceDetected as a,getStudySpaceExperienceFromPreference as l,resolveStudySpaceExperienceEnabled as c,syncStudySpaceExperiencePreferenceFromDetection as i}from"../../common/study-space-experience.js";jest.mock("../../common/local-storage.js",()=>({dcLocalStorage:{init:jest.fn().mockResolvedValue(void 0),getItem:jest.fn(),setItem:jest.fn(),removeItem:jest.fn()}})),describe("study-space-experience",()=>{beforeEach(()=>{jest.clearAllMocks()}),it("detects study space from browser mechanism or viewer eligibility",async()=>{e.getItem.mockImplementation(e=>e===n?JSON.stringify({[r]:"learner"}):null),await expect(a()).resolves.toBe(!0),e.getItem.mockImplementation(e=>e===t?"true":e===n?JSON.stringify({[r]:""}):null),await expect(a()).resolves.toBe(!0)}),it("prefers user preference over detection signals",async()=>{e.getItem.mockImplementation(e=>e===s?"true":e===o?"false":e===n?JSON.stringify({[r]:"learner"}):e===t?"true":null),await expect(c()).resolves.toBe(!1)}),it("reports master disabled when user explicitly turns off preference",async()=>{e.getItem.mockImplementation(e=>e===s?"true":e===o?"false":null),await expect(l()).resolves.toBe(!1),await expect(c()).resolves.toBe(!1)}),it("reports enabled when user explicitly turns on preference",async()=>{e.getItem.mockImplementation(e=>e===s||e===o?"true":null),await expect(l()).resolves.toBe(!0),await expect(c()).resolves.toBe(!0)}),it("returns null when user has not set preference",async()=>{e.getItem.mockReturnValue(null),await expect(l()).resolves.toBeNull()}),it("syncs cvXpEn from detection when user has not set preference",async()=>{e.getItem.mockImplementation(e=>e===t?"true":null),await i(),expect(e.setItem).toHaveBeenCalledWith(o,"true"),expect(e.removeItem).not.toHaveBeenCalled()}),it("clears cvXpEn when detection is off and user has not set preference",async()=>{e.getItem.mockReturnValue(null),await i(),expect(e.removeItem).toHaveBeenCalledWith(o),expect(e.setItem).not.toHaveBeenCalled()}),it("clears cvXpEn when browser tg is non_learner and account eligibility is cleared",async()=>{e.getItem.mockImplementation(e=>e===n?JSON.stringify({[r]:"non_learner"}):null),await expect(a()).resolves.toBe(!1),await expect(c()).resolves.toBe(!1)}),it("does not override cvXpEn after user sets preference",async()=>{e.getItem.mockImplementation(e=>e===s||e===t?"true":null),await i(),expect(e.setItem).not.toHaveBeenCalled(),expect(e.removeItem).not.toHaveBeenCalled()})});