/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
import{EVAR_KEYS as e,LOGGING_URI as t,CACHE_PURGE_SCHEME as o}from"../sw_modules/constant.js";import{dcLocalStorage as s}from"./local-storage.js";import{allowedLogs as n}from"../sw_modules/splunkAllowedLogs.js";import{util as r}from"../sw_modules/util.js";import{getActiveExperimentAnalyticsString as i}from"./experimentUtils.js";import a from"./splunkAllowedEvents.js";import{floodgate as l}from"../sw_modules/floodgate.js";function c(e){let t={};return e&&Object.entries(e).forEach(([e,o])=>{"object"==typeof o?t={...t,...c(o)}:t[e]=o}),t}function g(){return s.getItem("deferredLogs").map(t=>{const o=function(t){const o={...t};return Object.entries(e).forEach(([e,t])=>{Object.prototype.hasOwnProperty.call(o,e)&&(o[t]=o[e],delete o[e])}),o}(t.message);return c({...t,message:o})})}async function m(e){if(function(e){const t=s.getItem("blockedLogs");return t?.includes(e)}(e.message))return!1;if(s.getItem("disableLogWhitelisting")){if("analytics"===e.context){return!(!await l.hasFlag("dc-cv-enable-analytics-logging",o.NO_CALL)||!a.isEventAllowed(e.message))}return!0}const t=s.getItem("allowedLogIndex");return n[e.message]<=t}async function d(e,...t){const o=s.getItem("splunkLoggingEnable");if(!t.length||!t[0]||!1===o||!await m(t[0]))return;const n=t[0];if(n.context||(n.context="logger"),"undefined"!=typeof window&&window?.location)try{const e=new URLSearchParams(window.location.search).get("acrobatPromotionSource");e&&(n.acrobatPromotionSource=e)}catch(e){}!function(e){const t=s.getItem("deferredLogs")||[];t.push(e),s.setItem("deferredLogs",t)}({message:n,level:e,sessionId:s.getItem("sessionId"),variants:i(),anonUserUUID:s.getItem("anonUserUUID")})}const h=new class{constructor(){this.flushInterval=1e4,this.SERVER_PATH="/system/log",this.SERVER_CONTENT_TYPE='application/vnd.adobe.dc+json; profile="/schemas/system_log_parameters_v1.json"',this.loggingUri=t.prod,this.enableConsole=!1,setTimeout(()=>{const e=s.getItem("installSource"),o=s.getItem("env");"development"===e?(this.loggingUri=t.stage,this.enableConsole=!1):o&&t[o]&&(this.loggingUri=t[o])},250)}registerLogInterval(e){e?this.interval||(this.interval=setInterval(()=>{(s.getItem("deferredLogs")||[]).length>0&&this.flushLogs()},this.flushInterval)):(s.removeItem("deferredLogs"),clearInterval(this.interval))}flushLogs(){const e={headers:{"Content-Type":this.SERVER_CONTENT_TYPE.replace("/schemas/",`${this.loggingUri}/schemas/`),"x-request-id":r.uuid(),"x-api-app-info":"dc-acrobat-extension","x-api-client-id":`dc-acrobat-extension:${chrome.runtime.id}`}},t=g();this.enableConsole?console.log(t):fetch(this.loggingUri+this.SERVER_PATH,{method:"POST",headers:e.headers,body:JSON.stringify(t)}).catch(e=>console.log(e)),s.setItem("deferredLogs",[])}debug(...e){d("debug",...e)}info(...e){d("info",...e)}warn(...e){d("warn",...e)}error(...e){d("error",...e)}};export{h as loggingApi};