/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
import{loggingApi as e}from"../common/loggingApi.js";import t from"./CacheStore.js";import{floodgate as i}from"./floodgate.js";import{dcLocalStorage as s}from"../common/local-storage.js";import{isAddWebpageToProjectEnabled as r}from"./add-webpage-to-project.js";import{forceResetService as o}from"./force-reset-service.js";import{common as a}from"./common.js";const l=new class{constructor(){this.THIRTY_DAYS=2592e6,this.promise=null,this.promiseTimeoutDuration=18e5}async fetch(e){const t=await fetch(e);if(!t.ok)throw new Error(`Failed to fetch block list from ${e}: ${t.statusText}`);return(await t.text()).split("\n").map(e=>e.trim()).filter(e=>e.length>0)}async _get({blockListUrl:i,cacheKey:s,featureName:r}){const a=new t("explicit-blocklist");try{const e=async()=>{const e=await this.fetch(i);return e?.length>0&&await a.set(s,e),e||[]},{executionResult:t}=await o.executeFeature(r,e);if(t?.length>0)return t}catch(t){e.error({message:"Error fetching explicit block list from Adobe",error:t.toString(),blockListUrl:i})}return await a.get(s)||[]}async _getExplicitBlocklist(){await s.init();if(!await i.hasFlag("dc-cv-domain-moderation-enabled"))return[];const e={cacheKey:"explicitBlockList",blockListUrl:a.getModerationListUrl(),featureName:"common-moderation-list"};return await this._get(e)}async _getKWBlockList(){await s.init();const e=await i.hasFlag("dc-cv-kw-domain-moderation-enabled"),t=await r();if(!e||!t)return[];const o={cacheKey:"explicitBlockList-kw",blockListUrl:a.getKWModerationListUrl(),featureName:"kw-moderation-list"};return await this._get(o)}async _getExpressBlockList(){await s.init();if(!await i.hasFlag("dc-cv-express-moderation-enabled"))return[];const e={cacheKey:"explicitBlockList-express",blockListUrl:a.getExpressBlockListUrl(),featureName:"express-moderation-list"};return await this._get(e)}async _getExpressWebviewAllowedList(){await s.init();if(!await i.hasFlag("dc-cv-express-native-viewer-allow-list-enabled"))return[];const e={cacheKey:"explicitAllowList-expressWebview",blockListUrl:a.getExpressNativeViewerAllowListUri(),featureName:"express-native-viewer-moderation-list"};return await this._get(e)}async getExplicitBlocklist(){return this.promise||(this.promise=this._getExplicitBlocklist(),setTimeout(()=>{this.promise=null},this.promiseTimeoutDuration)),this.promise}async getKWBlockList(){return this.kwPromise||(this.kwPromise=this._getKWBlockList(),setTimeout(()=>{this.kwPromise=null},this.promiseTimeoutDuration)),this.kwPromise}async getExpressBlockList(){return this.expressPromise||(this.expressPromise=this._getExpressBlockList(),setTimeout(()=>{this.expressPromise=null},this.promiseTimeoutDuration)),this.expressPromise}async getExpressWebviewAllowedList(){return this.expressWebviewAllowedListPromise||(this.expressWebviewAllowedListPromise=this._getExpressWebviewAllowedList(),setTimeout(()=>{this.expressWebviewAllowedListPromise=null},this.promiseTimeoutDuration)),this.expressWebviewAllowedListPromise}};export default l;