/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
import{STUDENT_TOOLS_TOUCHPOINT_REGISTRY as e,STUDENT_TOOLS_TOUCHPOINT_SEARCH_ORDER as t,getStudentToolsTouchpointConfig as o,getTouchpointsForSurface as n}from"./student-tools-touchpoint-registry.js";describe('notes (FAB "Generate notes" challenger)',()=>{it("is fab-only, with its own distinct fabRoutingContext for analytics attribution (not study-guide's, not the unrelated 'generateNotes' Notes-tab funnel)",()=>{const e=o("notes"),t=o("study-guide");expect(e.surfaces).toEqual(["fab"]),expect(e.fabRoutingContext).toBe("ExtensionFAB:generateNotesStudyGuide"),expect(e.fabRoutingContext).not.toBe(t.fabRoutingContext),expect(e.fabRoutingContext).not.toBe("ExtensionFAB:generateNotes"),expect(e.googleSearchRoutingContext).toBeUndefined(),expect(e.contextMenuRoutingContext).toBeUndefined()}),it("has a fabLabelKey distinct from translationTitleKey conceptually but present for the FAB pill",()=>{const e=o("notes");expect(e.fabLabelKey).toBe("studentToolsTouchpointFabNotes"),expect(e.translationTitleKey).toBeTruthy()}),it("is included when filtering touchpoints for the fab surface",()=>{expect(n("fab").map(e=>e.id)).toContain("notes")}),it("is not included when filtering touchpoints for the google-search surface",()=>{expect(n("google-search").map(e=>e.id)).not.toContain("notes")})}),describe("cheatsheet (Google Search widget)",()=>{it("is google-search-only, with a googleSearchRoutingContext matching the dc-hosted-extension mirror casing",()=>{const e=o("cheatsheet");expect(e.surfaces).toEqual(["google-search"]),expect(e.googleSearchRoutingContext).toBe("ExtensionGoogleSearchResult:generateCheatSheet"),expect(e.fabRoutingContext).toBeUndefined(),expect(e.contextMenuRoutingContext).toBeUndefined()}),it("is included when filtering touchpoints for the google-search surface",()=>{expect(n("google-search").map(e=>e.id)).toContain("cheatsheet")}),it("is not included when filtering touchpoints for the fab surface",()=>{expect(n("fab").map(e=>e.id)).not.toContain("cheatsheet")}),it("is present in the search-term resolution order",()=>{expect(t).toContain("cheatsheet")})}),describe("STUDENT_TOOLS_TOUCHPOINT_REGISTRY — every entry",()=>{it("declares fabRoutingContext for every touchpoint whose surfaces include fab",()=>{Object.values(e).filter(e=>e.surfaces.includes("fab")).forEach(e=>{expect(e.fabRoutingContext).toBeTruthy(),expect(e.fabLabelKey).toBeTruthy()})}),it("declares googleSearchRoutingContext for every touchpoint whose surfaces include google-search",()=>{Object.values(e).filter(e=>e.surfaces.includes("google-search")).forEach(e=>{expect(e.googleSearchRoutingContext).toBeTruthy()})}),it("declares contextMenuRoutingContext and contextMenuId for every touchpoint whose surfaces include context-menu",()=>{Object.values(e).filter(e=>e.surfaces.includes("context-menu")).forEach(e=>{expect(e.contextMenuRoutingContext).toBeTruthy(),expect(e.contextMenuId).toBeTruthy()})})});