/*************************************************************************
* ADOBE CONFIDENTIAL
* ___________________
*
*  Copyright 2015 Adobe Systems Incorporated
*  All Rights Reserved.
*
* NOTICE:  All information contained herein is, and remains
* the property of Adobe Systems Incorporated and its suppliers,
* if any.  The intellectual and technical concepts contained
* herein are proprietary to Adobe Systems Incorporated and its
* suppliers and are protected by all applicable intellectual property laws,
* including trade secret and or copyright laws.
* Dissemination of this information or reproduction of this material
* is strictly forbidden unless prior written permission is obtained
* from Adobe Systems Incorporated.
**************************************************************************/
"use strict";import{createAcrobatIconElement}from"../utils/util.js";import{shouldShowFteTooltip,createFteTooltip,updateFteToolTipCoolDown,acrobatTouchPointClicked,initFteStateAndConfig,addFteCloseButtonListener,removeFteTooltip}from"../utils/fte-utils.js";import{executeVerb,processFileUrl,fireTouchpointAnalytics}from"./verb-execution-service.js";export function createTouchpointController(e,t){const o=`ac-${e.surface}-${e.verb}-processed-x3k9f`,r=e.fteStorageKey||`ac-${e.surface}-${e.verb}-fte`;return{get isEnabled(){return e.enabled},get isControl(){return e.controlEnabled},get fteType(){return e.fteType},get config(){return e},markProcessed(e){e&&e.setAttribute(o,"Y")},isProcessed:e=>"Y"===e?.getAttribute(o),createIcon:e=>createAcrobatIconElement(e,t?.iconURL||"browser/images/acrobat_dc_appicon_128.png"),createTextElement(t){const o=document.createElement("span");return o.classList.add(t),o.textContent=e.touchPointText,o},onShow(t){fireTouchpointAnalytics("Shown",{source:`${e.promotionSourcePrefix}:${e.promotionSourceSuffix}`,workflow:e.verb,eventContext:t})},onClick({fileUrl:o,fileName:i,mimeType:n,urlProcessOptions:c={},inactiveTabDirectVerbProcessingEnabled:s=e.inactiveTabDirectVerbProcessingEnabled,authContext:a,directVerbSessionId:l}){const u=processFileUrl(o,e.verb,c);executeVerb({fileUrl:u,fileName:i,verb:e.verb,promotionSourcePrefix:e.promotionSourcePrefix,promotionSourceSuffix:e.promotionSourceSuffix,viewerURLPrefix:t?.viewerURLPrefix,inactiveTabDirectVerbProcessingEnabled:s,authContext:a,directVerbSessionId:l}),fireTouchpointAnalytics("Clicked",{source:`${e.promotionSourcePrefix}:${e.promotionSourceSuffix}`,workflow:e.verb,eventContext:n}),acrobatTouchPointClicked(r);try{chrome.runtime.sendMessage({main_op:"akamai-ping"})}catch(e){}},async tryShowFte(t,o,i){if(!e.enableFte||!e.fteConfig?.tooltip)return;const n=await initFteStateAndConfig(r);await shouldShowFteTooltip(e.fteConfig.tooltip,n,e.enableFte)?i(!0,()=>{const i=createFteTooltip(e.fteTooltipStrings,o),n={source:`${e.promotionSourcePrefix}:${e.promotionSourceSuffix}`,workflow:e.verb},c=e=>{const t="click"===e.type&&!i.contains(e.target),o="keydown"===e.type&&"Escape"===e.key;(t||o)&&(removeFteTooltip(),document.removeEventListener("click",c),document.removeEventListener("keydown",c))};addFteCloseButtonListener(i,{fteType:o,onClose:()=>{document.removeEventListener("click",c),document.removeEventListener("keydown",c),fireTouchpointAnalytics("Fte:Closed",n)}}),i.clickOutsideHandler=e=>{i.contains(e.target)||(removeFteTooltip(),fireTouchpointAnalytics("Fte:Dismissed",n))},t.appendChild(i),updateFteToolTipCoolDown(e.fteConfig.tooltip,r),fireTouchpointAnalytics("Fte:Shown",n),document.addEventListener("click",c),document.addEventListener("keydown",c)}):i(!1)},get processedAttribute(){return o},getFileExtToMimeTypeMap:()=>e.metadata?.fileExtToMimeTypeMap||{},getSelectors:()=>e.metadata?.selectors||[]}}